In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, models
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

# -----------------------------
# 1) 데이터 불러오기
# -----------------------------

(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step


In [2]:
# -----------------------------
# 2) 정규화 (0~1) 및 텐서 변환
# -----------------------------

x_train = x_train.astype("float32") / 255.0
x_test  = x_test.astype("float32") / 255.0

In [3]:
# -----------------------------
# 3) 채널 차원 추가
# -----------------------------

x_train = x_train[..., tf.newaxis]  # (60000, 28, 28, 1)
x_test  = x_test[..., tf.newaxis]   # (10000, 28, 28, 1)

In [4]:
# -----------------------------
# 4) CNN 모델 구성
# -----------------------------

model = models.Sequential([
    layers.Input(shape=(28, 28, 1)),
    layers.Conv2D(32, 3, padding='same', activation='relu'),
    layers.MaxPooling2D(),
    layers.Conv2D(64, 3, padding='same', activation='relu'),
    layers.Flatten(),
    layers.Dropout(0.3),
    layers.Dense(128, activation='relu'),
    layers.Dense(10, activation='softmax')
])

In [5]:
# -----------------------------
# 5) 모델 컴파일
# -----------------------------

model.compile(
        optimizer='adam',
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy'])

In [6]:
# 모델 요약 정보 출력
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 28, 28, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 14, 14, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 14, 14, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 12544)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 12544)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │     1,605,760 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,625,866 (6.20 MB)

 Trainable params: 1,625,866 (6.20 MB)

 Non-trainable params: 0 (0.00 B)

In [7]:
# -----------------------------
# 6) 모델 학습
# -----------------------------

history = model.fit(
    x_train, y_train,
    epochs=10,
    batch_size=64,
    validation_split=0.1,
    verbose=2
)

Epoch 1/10
844/844 - 11s - 13ms/step - accuracy: 0.9545 - loss: 0.1464 - val_accuracy: 0.9842 - val_loss: 0.0585
Epoch 2/10
844/844 - 3s - 4ms/step - accuracy: 0.9855 - loss: 0.0462 - val_accuracy: 0.9897 - val_loss: 0.0385
Epoch 3/10
844/844 - 3s - 3ms/step - accuracy: 0.9899 - loss: 0.0313 - val_accuracy: 0.9907 - val_loss: 0.0391
Epoch 4/10
844/844 - 3s - 3ms/step - accuracy: 0.9919 - loss: 0.0234 - val_accuracy: 0.9895 - val_loss: 0.0399
Epoch 5/10
844/844 - 3s - 3ms/step - accuracy: 0.9944 - loss: 0.0166 - val_accuracy: 0.9930 - val_loss: 0.0327
Epoch 6/10
844/844 - 3s - 4ms/step - accuracy: 0.9953 - loss: 0.0144 - val_accuracy: 0.9917 - val_loss: 0.0378
Epoch 7/10
844/844 - 5s - 5ms/step - accuracy: 0.9958 - loss: 0.0122 - val_accuracy: 0.9907 - val_loss: 0.0363
Epoch 8/10
844/844 - 3s - 3ms/step - accuracy: 0.9970 - loss: 0.0093 - val_accuracy: 0.9908 - val_loss: 0.0409
Epoch 9/10
844/844 - 3s - 4ms/step - accuracy: 0.9970 - loss: 0.0090 - val_accuracy: 0.9897 - val_loss: 0.0479

In [12]:
# -----------------------------
# 7) 모델 평가
# -----------------------------

test_loss, test_acc = model.evaluate(x_test, y_test, verbose=0)
print(f"Test Accuracy: {test_acc:.4f}")

Test Accuracy: 0.9921


In [13]:
# -----------------------------
# 8) 모델 예측
# -----------------------------

y_pred = np.argmax(model.predict(x_test), axis=1)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


In [14]:
# -----------------------------
# 9) 평가 지표: 레포트/혼동행렬
# -----------------------------

print("Classification Report:")
print(classification_report(y_test, y_pred, digits=4))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0     0.9949    0.9959    0.9954       980
           1     0.9930    0.9982    0.9956      1135
           2     0.9847    0.9961    0.9904      1032
           3     0.9941    0.9941    0.9941      1010
           4     0.9939    0.9949    0.9944       982
           5     0.9834    0.9944    0.9889       892
           6     0.9916    0.9916    0.9916       958
           7     0.9941    0.9874    0.9907      1028
           8     0.9958    0.9846    0.9902       974
           9     0.9950    0.9832    0.9890      1009

    accuracy                         0.9921     10000
   macro avg     0.9920    0.9920    0.9920     10000
weighted avg     0.9921    0.9921    0.9921     10000

Confusion Matrix:
[[ 976    1    0    0    0    0    1    1    1    0]
 [   0 1133    1    1    0    0    0    0    0    0]
 [   0    1 1028    1    0    0    1    1    0    0]
 [   0    0    1 1004    0    4    0    0

In [15]:
# 샘플 예측 확인
predictions = model.predict(x_test[:5])
print("예측 결과:", np.argmax(predictions, axis=1))
print("실제 레이블:", y_test[:5])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
예측 결과: [7 2 1 0 4]
실제 레이블: [7 2 1 0 4]
