In [2]:
import tensorflow as tf
from tensorflow.keras import layers, models
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

# -----------------------------
# 1) 데이터 불러오기
# -----------------------------

fashion_mnist = tf.keras.datasets.fashion_mnist
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

29515/29515 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
26421880/26421880 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
5148/5148 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
4422102/4422102 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [3]:
# -----------------------------
# 2) 클래스 이름(라벨 이름) 정의
# -----------------------------

class_names = [
    "T-shirt/top","Trouser","Pullover","Dress","Coat",
    "Sandal","Shirt","Sneaker","Bag","Ankle boot"
]

In [4]:
# -----------------------------
# 3) 정규화 (0~1)
# -----------------------------

x_train = x_train / 255.0
x_test = x_test / 255.0

In [5]:
# -----------------------------
# 4) DNN 모델 구성
# -----------------------------

model = models.Sequential([
    layers.Flatten(input_shape=(28, 28)),
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(10, activation='softmax')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [6]:
# -----------------------------
# 5) 모델 컴파일
# -----------------------------

model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

In [7]:
# 모델 요약 정보 출력
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten (Flatten)               │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 256)            │       200,960 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 128)            │        32,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 10)             │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 235,146 (918.54 KB)

 Trainable params: 235,146 (918.54 KB)

 Non-trainable params: 0 (0.00 B)

In [8]:
# -----------------------------
# 6) 모델 학습
# -----------------------------

history = model.fit(
    x_train, y_train,
    epochs=10,
    validation_split=0.1,
    batch_size=128,
    verbose=2
)

Epoch 1/10
422/422 - 5s - 12ms/step - accuracy: 0.7696 - loss: 0.6454 - val_accuracy: 0.8478 - val_loss: 0.4090
Epoch 2/10
422/422 - 5s - 11ms/step - accuracy: 0.8410 - loss: 0.4410 - val_accuracy: 0.8602 - val_loss: 0.3806
Epoch 3/10
422/422 - 3s - 8ms/step - accuracy: 0.8550 - loss: 0.4012 - val_accuracy: 0.8688 - val_loss: 0.3608
Epoch 4/10
422/422 - 4s - 8ms/step - accuracy: 0.8644 - loss: 0.3748 - val_accuracy: 0.8727 - val_loss: 0.3417
Epoch 5/10
422/422 - 5s - 13ms/step - accuracy: 0.8679 - loss: 0.3580 - val_accuracy: 0.8773 - val_loss: 0.3315
Epoch 6/10
422/422 - 3s - 8ms/step - accuracy: 0.8741 - loss: 0.3447 - val_accuracy: 0.8773 - val_loss: 0.3346
Epoch 7/10
422/422 - 3s - 8ms/step - accuracy: 0.8776 - loss: 0.3335 - val_accuracy: 0.8777 - val_loss: 0.3389
Epoch 8/10
422/422 - 3s - 8ms/step - accuracy: 0.8816 - loss: 0.3217 - val_accuracy: 0.8780 - val_loss: 0.3288
Epoch 9/10
422/422 - 5s - 11ms/step - accuracy: 0.8836 - loss: 0.3135 - val_accuracy: 0.8838 - val_loss: 0.31

In [9]:
# -----------------------------
# 7) 모델 평가
# -----------------------------

test_loss, test_acc = model.evaluate(x_test, y_test, verbose=2)
print(f"Test Accuracy: {test_acc:.4f}")

313/313 - 1s - 2ms/step - accuracy: 0.8767 - loss: 0.3498
Test Accuracy: 0.8767


In [10]:
# -----------------------------
# 8) 모델 예측
# -----------------------------

y_pred_prob = model.predict(x_test, verbose=0)
y_pred = np.argmax(y_pred_prob, axis=1)

In [11]:
# -----------------------------
# 9) 평가 지표: 레포트/혼동행렬
# -----------------------------

print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=class_names, digits=4))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

 T-shirt/top     0.7652    0.9060    0.8297      1000
     Trouser     0.9969    0.9600    0.9781      1000
    Pullover     0.7326    0.8520    0.7878      1000
       Dress     0.8822    0.8910    0.8866      1000
        Coat     0.8025    0.7600    0.7807      1000
      Sandal     0.9894    0.9370    0.9625      1000
       Shirt     0.7730    0.5620    0.6508      1000
     Sneaker     0.9164    0.9750    0.9448      1000
         Bag     0.9692    0.9740    0.9716      1000
  Ankle boot     0.9596    0.9500    0.9548      1000

    accuracy                         0.8767     10000
   macro avg     0.8787    0.8767    0.8747     10000
weighted avg     0.8787    0.8767    0.8747     10000

Confusion Matrix:
[[906   0  16  17   3   0  52   0   6   0]
 [  9 960   1  24   3   0   1   0   2   0]
 [ 21   0 852  10  75   0  39   0   3   0]
 [ 43   2  12 891  30   0  19   0   3   0]
 [  0   0 152  37 760   0  5

In [12]:
# 샘플 예측 확인
idx = np.arange(5)
print("샘플 예측:", [class_names[i] for i in y_pred[idx]])
print("실제 레이블:", [class_names[i] for i in y_test[idx]])

샘플 예측: ['Ankle boot', 'Pullover', 'Trouser', 'Trouser', 'Shirt']
실제 레이블: ['Ankle boot', 'Pullover', 'Trouser', 'Trouser', 'Shirt']
