In [1]:
import tensorflow as tf
from tensorflow.keras import layers, models
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

# -----------------------------
# 1) 데이터 불러오기
# -----------------------------

fashion_mnist = tf.keras.datasets.fashion_mnist
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

29515/29515 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
26421880/26421880 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
5148/5148 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
4422102/4422102 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [2]:
# -----------------------------
# 2) 클래스 이름(라벨 이름) 정의
# -----------------------------

class_names = [
    "T-shirt/top","Trouser","Pullover","Dress","Coat",
    "Sandal","Shirt","Sneaker","Bag","Ankle boot"
]

In [3]:
# -----------------------------
# 3) 정규화 (0~1)
# -----------------------------

x_train = x_train / 255.0
x_test = x_test / 255.0

In [4]:
# -----------------------------
# 4) 채널 차원 추가
# -----------------------------

x_train = np.expand_dims(x_train, -1)
x_test = np.expand_dims(x_test, -1)

print("x_train shape:", x_train.shape)  # (60000, 28, 28, 1)
print("x_test shape:", x_test.shape)    # (10000, 28, 28, 1)

x_train shape: (60000, 28, 28, 1)
x_test shape: (10000, 28, 28, 1)


In [5]:
# -----------------------------
# 5) CNN 모델 구성
# -----------------------------

model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(128, (3, 3), activation='relu'),
    layers.Flatten(),
    layers.Dropout(0.4),
    layers.Dense(128, activation='relu'),
    layers.Dense(10, activation='softmax')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [6]:
# -----------------------------
# 6) 모델 컴파일
# -----------------------------

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [7]:
# 모델 요약 정보 출력
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                 │ (None, 26, 26, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 13, 13, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 11, 11, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 5, 5, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 3, 3, 128)      │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 1152)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 1152)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │       147,584 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 10)             │         1,290 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 241,546 (943.54 KB)

 Trainable params: 241,546 (943.54 KB)

 Non-trainable params: 0 (0.00 B)

In [8]:
# -----------------------------
# 7) 모델 학습
# -----------------------------

history = model.fit(
    x_train, y_train,
    epochs=10,
    batch_size=128,
    validation_split=0.1,
    verbose=2
)

Epoch 1/10
422/422 - 11s - 26ms/step - accuracy: 0.7671 - loss: 0.6286 - val_accuracy: 0.8527 - val_loss: 0.4019
Epoch 2/10
422/422 - 2s - 4ms/step - accuracy: 0.8564 - loss: 0.3976 - val_accuracy: 0.8707 - val_loss: 0.3510
Epoch 3/10
422/422 - 2s - 4ms/step - accuracy: 0.8745 - loss: 0.3433 - val_accuracy: 0.8890 - val_loss: 0.3035
Epoch 4/10
422/422 - 2s - 4ms/step - accuracy: 0.8879 - loss: 0.3067 - val_accuracy: 0.8908 - val_loss: 0.2977
Epoch 5/10
422/422 - 2s - 4ms/step - accuracy: 0.8950 - loss: 0.2826 - val_accuracy: 0.9012 - val_loss: 0.2710
Epoch 6/10
422/422 - 2s - 4ms/step - accuracy: 0.9024 - loss: 0.2647 - val_accuracy: 0.9060 - val_loss: 0.2605
Epoch 7/10
422/422 - 2s - 5ms/step - accuracy: 0.9085 - loss: 0.2484 - val_accuracy: 0.9082 - val_loss: 0.2450
Epoch 8/10
422/422 - 2s - 5ms/step - accuracy: 0.9136 - loss: 0.2352 - val_accuracy: 0.9052 - val_loss: 0.2592
Epoch 9/10
422/422 - 2s - 4ms/step - accuracy: 0.9181 - loss: 0.2241 - val_accuracy: 0.9148 - val_loss: 0.2313

In [9]:
# -----------------------------
# 8) 모델 평가
# -----------------------------

test_loss, test_acc = model.evaluate(x_test, y_test, verbose=2)
print(f"\nTest Accuracy: {test_acc:.4f}")

313/313 - 2s - 6ms/step - accuracy: 0.9084 - loss: 0.2471

Test Accuracy: 0.9084


In [10]:
# -----------------------------
# 9) 모델 예측
# -----------------------------

y_pred = np.argmax(model.predict(x_test), axis=1)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step


In [11]:
# -----------------------------
# 10) 평가 지표: 레포트/혼동행렬
# -----------------------------

print("Classification Report:")
print(classification_report(y_test, y_pred, target_names=class_names, digits=4))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

 T-shirt/top     0.8414    0.8910    0.8655      1000
     Trouser     0.9840    0.9830    0.9835      1000
    Pullover     0.8281    0.8770    0.8519      1000
       Dress     0.9239    0.8990    0.9113      1000
        Coat     0.8354    0.8780    0.8562      1000
      Sandal     0.9840    0.9850    0.9845      1000
       Shirt     0.7698    0.6720    0.7176      1000
     Sneaker     0.9574    0.9670    0.9622      1000
         Bag     0.9868    0.9700    0.9783      1000
  Ankle boot     0.9698    0.9620    0.9659      1000

    accuracy                         0.9084     10000
   macro avg     0.9081    0.9084    0.9077     10000
weighted avg     0.9081    0.9084    0.9077     10000

Confusion Matrix:
[[891   2  30  14   4   1  56   0   2   0]
 [  1 983   0  11   2   0   1   0   2   0]
 [ 13   0 877   7  59   0  44   0   0   0]
 [ 12  12  15 899  37   0  22   0   3   0]
 [  0   0  37  14 878   0  7

In [12]:
# 샘플 예측 확인
predictions = model.predict(x_test[:5])
print("예측 결과:", np.argmax(predictions, axis=1))
print("실제 레이블:", y_test[:5])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 444ms/step
예측 결과: [9 2 1 1 6]
실제 레이블: [9 2 1 1 6]
