In [ ]:
import tensorflow as tf
from tensorflow.keras import layers, models
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

# -----------------------------
# 1) 데이터 불러오기
# -----------------------------
fashion_mnist = tf.keras.datasets.fashion_mnist
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

In [ ]:
class_names = [
    "T-shirt/top","Trouser","Pullover","Dress","Coat",
    "Sandal","Shirt","Sneaker","Bag","Ankle boot"
]

In [ ]:
# -----------------------------
# 2) 정규화 (0~1)
# -----------------------------

x_train = x_train / 255.0
x_test = x_test / 255.0

In [ ]:
# -----------------------------
# 3) DNN 모델 구성
# -----------------------------

model = models.Sequential([
    layers.Flatten(input_shape=(28, 28)),
    layers.Dense(256, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.3),
    layers.Dense(10, activation='softmax')
])

In [ ]:
# -----------------------------
# 4) 모델 컴파일
# -----------------------------

model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

In [ ]:
# 모델 요약 정보 출력
model.summary()

In [ ]:
# -----------------------------
# 5) 모델 학습
# -----------------------------

history = model.fit(x_train, y_train, epochs=10,
                            validation_split=0.1, batch_size=128, verbose=2)

Epoch 1/10
422/422 - 7s - 18ms/step - accuracy: 0.7736 - loss: 0.6356 - val_accuracy: 0.8400 - val_loss: 0.4288
Epoch 2/10
422/422 - 4s - 8ms/step - accuracy: 0.8422 - loss: 0.4372 - val_accuracy: 0.8703 - val_loss: 0.3690
Epoch 3/10
422/422 - 4s - 9ms/step - accuracy: 0.8573 - loss: 0.3954 - val_accuracy: 0.8650 - val_loss: 0.3651
Epoch 4/10
422/422 - 5s - 12ms/step - accuracy: 0.8664 - loss: 0.3714 - val_accuracy: 0.8742 - val_loss: 0.3406
Epoch 5/10
422/422 - 4s - 10ms/step - accuracy: 0.8698 - loss: 0.3553 - val_accuracy: 0.8808 - val_loss: 0.3329
Epoch 6/10
422/422 - 4s - 8ms/step - accuracy: 0.8746 - loss: 0.3423 - val_accuracy: 0.8795 - val_loss: 0.3222
Epoch 7/10
422/422 - 6s - 14ms/step - accuracy: 0.8800 - loss: 0.3283 - val_accuracy: 0.8788 - val_loss: 0.3206
Epoch 8/10
422/422 - 5s - 12ms/step - accuracy: 0.8817 - loss: 0.3216 - val_accuracy: 0.8843 - val_loss: 0.3248
Epoch 9/10
422/422 - 5s - 11ms/step - accuracy: 0.8844 - loss: 0.3131 - val_accuracy: 0.8838 - val_loss: 0.

In [ ]:
# -----------------------------
# 6) 모델 평가
# -----------------------------
test_loss, test_acc = model.evaluate(x_test, y_test, verbose=2)
print(f"DNN Test Accuracy: {test_acc:.4f}")

313/313 - 1s - 3ms/step - accuracy: 0.8818 - loss: 0.3289
DNN Test Accuracy: 0.8818


In [ ]:
# -----------------------------
# 7) 모델 예측 + 리포트/혼동행렬
# -----------------------------

y_pred_prob = model.predict(x_test, verbose=0)
y_pred = np.argmax(y_pred_prob, axis=1)

print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=class_names, digits=4))

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)



Classification Report:
              precision    recall  f1-score   support

 T-shirt/top     0.8204    0.8590    0.8393      1000
     Trouser     0.9731    0.9780    0.9756      1000
    Pullover     0.8189    0.7550    0.7856      1000
       Dress     0.8888    0.8870    0.8879      1000
        Coat     0.6885    0.8840    0.7741      1000
      Sandal     0.9853    0.9390    0.9616      1000
       Shirt     0.7650    0.5500    0.6399      1000
     Sneaker     0.9541    0.9360    0.9450      1000
         Bag     0.9551    0.9780    0.9664      1000
  Ankle boot     0.9185    0.9800    0.9482      1000

    accuracy                         0.8746     10000
   macro avg     0.8768    0.8746    0.8724     10000
weighted avg     0.8768    0.8746    0.8724     10000

Confusion Matrix:
 [[859   6  12  21   8   0  87   0   7   0]
 [  2 978   0  15   3   0   0   0   2   0]
 [ 16   0 755  10 175   0  40   0   4   0]
 [ 21  16  11 887  42   0  18   0   5   0]
 [  0   1  54  36 884   0 

In [ ]:
# 샘플 확인
idx = np.arange(5)
print("\n샘플 예측:", [class_names[i] for i in y_pred[idx]])
print("실제 레이블:", [class_names[i] for i in y_test[idx]])


샘플 예측: ['Ankle boot', 'Pullover', 'Trouser', 'Trouser', 'Shirt']
실제 레이블: ['Ankle boot', 'Pullover', 'Trouser', 'Trouser', 'Shirt']
